### ISSUE TITLE
Initial bootstrap for Postgres fails w/ El Capitan + Postgres 9.5.3

### ISSUE THREAD

**Issue by Tristor** [go-bootstrap/go-bootstrap#47] opened 2016-07-15 14:40 UTC
```
$GOPATH/bin/go-bootstrap -dir github.com/tristor/projectname -template postgresql
2016/07/15 16:35:46 Creating /Users/tristor/projects/go/src/github.com/tristor/projectname...
2016/07/15 16:35:46 Copying project template directory to /Users/tristor/projects/go/src/github.com/tristor/projectname...
2016/07/15 16:35:46 Replacing placeholder variables on tristor/projectname...
2016/07/15 16:35:46 Running go get -u github.com/rnubel/pgmgr...
2016/07/15 16:35:50 Creating database projectname...

Database projectname created successfully.
Running migrations...
== Applying 0001_basic-schema.up.sql ==
== Completed in 7 ms ==
Creating database projectname-test
createdb: database creation failed: ERROR:  database "projectname" already exists

Error:  exit status 1

Running migration on postgres://tristor@localhost:5432/projectname-test?sslmode=disable...
Nothing to do; all migrations already applied.
2016/07/15 16:35:50 Running go get ./...
2016/07/15 16:35:51 Running go test ./...
2016/07/15 16:35:52 ?   	github.com/tristor/projectname	[no test files]
?   	github.com/tristor/projectname/application	[no test files]
?   	github.com/tristor/projectname/handlers	[no test files]
ok  	github.com/tristor/projectname/libhttp	0.007s
ok  	github.com/tristor/projectname/libstring	0.007s
ok  	github.com/tristor/projectname/libunix	0.015s
?   	github.com/tristor/projectname/middlewares	[no test files]
--- FAIL: TestNewTransactionIfNeeded (0.01s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
--- FAIL: TestCreateDeleteGeneric (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
--- FAIL: TestCreateDeleteById (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
--- FAIL: TestCreateUpdateGenericDelete (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
--- FAIL: TestCreateUpdateByIDDelete (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
--- FAIL: TestCreateUpdateByKeyValueStringDelete (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
--- FAIL: TestUserCRUD (0.01s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "projectname-test" does not exist
FAIL
FAIL	github.com/tristor/projectname/models	0.045s
```

I've replaced the name of the project with the placeholder `projectname` above, but this is otherwise the unmodified output when running the initial bootstrap on OS X El Capitan w/ PostgreSQL 9.5.3 installed via Homebrew on a clean database (pg_ctl initdb performed before hand).

It looks like the migrations performed by `pgmgr` fail because it creates the `projectname` database and during the attempted creation of the `projectname-test` database, it attempts to create the `projectname` database again, which of course already exists.

Any thoughts?

Additional system info:
```
❯ go version
go version go1.6.2 darwin/amd64
❯ uname -a
Darwin TRMBP15 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
❯ postgres --version
postgres (PostgreSQL) 9.5.3
```

**Comment by rnubel** [comment] 2016-07-15 15:47
Can you try running `$GOPATH/bin/pgmgr -c .pgmgr.test.json db create` in the root of your project and see if it throws the same error? I'd also be interested in seeing the output of `$GOPATH/bin/pgmgr -c .pgmgr.test.json config`.

**Comment by Tristor** [comment] 2016-07-15 17:36
Sure, no problem.  Here's the information you requested.

```
❯ $GOPATH/bin/pgmgr -c .pgmgr.test.json db create
createdb: database creation failed: ERROR:  database "projectname" already exists

Error:  exit status 1

❯ $GOPATH/bin/pgmgr -c .pgmgr.test.json config
&{Username:tristor Password: Database:projectname Host:localhost Port:5432 URL:postgres://tristor@localhost:5432/projectname-test?sslmode=disable SslMode:disable DumpFile:migrations/dump.sql MigrationFolder:migrations MigrationTable:schema_migrations SeedTables:[] ColumnType:integer Format:unix}
```

**Comment by rnubel** [comment] 2016-07-15 18:52
Odd. The problem is that the database name is being set to `projectname` instead of `projectname-test`, though I'm not clear on why. My first thought was the dash was breaking the DSN parsing, but locally it works fine for me:

```
> $GOPATH/bin/pgmgr -c .pgmgr.json config

&{Username:robert Password: Database:robert-test Host:localhost Port:5432 URL:postgres://robert@localhost:5432/robert-test?sslmode=verify-ca SslMode:verify-ca DumpFile:migrations/dump.sql MigrationFolder:migrations MigrationTable:schema_migrations SeedTables:[] ColumnType:integer Format:unix}
```

I'm on Yosemite, not El Capitan, but it's hard to imagine that making a difference. And the URL's options should be overriding every other source of configuration, so your environment shouldn't affect it. If you're open to adding some debugging information to your local copy of `pgmgr`, I would definitely want to start by logging what the regexp match data looks like [here](https://github.com/rnubel/pgmgr/blob/befdf7ebf3f88904c2ca6b6947ff6e8a9b6402d8/pgmgr/config.go#L166).

**Comment by Tristor** [comment] 2016-07-15 21:33
Thanks for your involvement in this issue.  I hadn't realized before, but did so when I clicked your link regarding the additional logging that you're the author of `pgmgr`.

I added the following in pgmgr/pgmgr/config.go with the block where you recommended:
```
		// This is hacky debugging logic added in relation to go-bootstrap Issue #47
		o := []byte(config.Database)
		err := ioutil.WriteFile("/tmp/issue47.log", o, 0644)
		if err != nil {
			fmt.Println("Error writing out issue47.log", err)
		}
```

Inside of `/tmp/issue47.log` after rerunning `$GOPATH/bin/pgmgr -c .pgmgr.test.json config` from the project directory, I get the string `projectname`. 

I must confess, regular expressions aren't my forte, so I don't fully understand exactly how `FindStringSubmatch` interacts with the URL based on the regexp provided.  Looking at it though, it's clear that it's cutting off `-test` because it /is/ present in the URL.

**Comment by rnubel** [comment] 2016-07-16 05:35
Thanks for being willing to dig into this! Unfortunately, I'm not sure what's going on. The regexp is valid (you can try it out online: http://fiddle.re/ed9nha), which means either the URL isn't what it should be, or something really weird is going on with the regexp behavior (very unlikely). Would you mind amending your debug script to:

```go
fmt.Println("-- Start Issue 47 Log --")
fmt.Printf("%+v\n", config.URL)
fmt.Printf("%+v\n", config.Database)
fmt.Printf("%+v\n", m)
fmt.Println("-- End Issue 47 Log --")
```

This will just display data in your terminal as you run the `pgmgr db create` command. My best thought now is that perhaps config.URL is not what we expect, though I don't see how...

**Comment by Tristor** [comment] 2016-07-16 16:50
Sorry it took me so long to respond, I was at a wine-tasting in out of the city I'm staying in today (I'm currently traveling).

```
❯ $GOPATH/bin/pgmgr -c .pgmgr.test.json config
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/projectname-test?sslmode=disable
projectname
[postgres://tristor@localhost:5432/projectname tristor localhost 5432 projectname]
-- End Issue 47 Log --
&{Username:tristor Password: Database:projectname Host:localhost Port:5432 URL:postgres://tristor@localhost:5432/projectname-test?sslmode=disable SslMode:disable DumpFile:migrations/dump.sql MigrationFolder:migrations MigrationTable:schema_migrations SeedTables:[] ColumnType:integer Format:unix}
```

Based on seeing this, it appears that `m` doesn't contain the correct URL, instead it contains the URL with `-test` stripped, although `config.URL` contains the complete URL.  So it's something about how it's being tokenized during the RegExp.

**Comment by didip** [comment] 2016-07-18 00:42
Hi @Tristor @rnubel 

Sorry for the late reply, I am still trying to reproduce this on my environment. Both `projectname` and `projectname-test` are created just fine:

* OS X El Capitan

* postgres (PostgreSQL) 9.5.0

**Output**
```
didip@didip-mac-mini [~]  go install github.com/go-bootstrap/go-bootstrap
didip@didip-mac-mini [~]  $GOPATH/bin/go-bootstrap -dir github.com/tristor/projectname -template postgresql
2016/07/17 17:36:35 Creating /Users/didip/go/src/github.com/tristor/projectname...
2016/07/17 17:36:35 Copying project template directory to /Users/didip/go/src/github.com/tristor/projectname...
2016/07/17 17:36:36 Replacing placeholder variables on tristor/projectname...
2016/07/17 17:36:36 Running go get -u github.com/rnubel/pgmgr...
2016/07/17 17:36:49 Creating database projectname...

Database projectname created successfully.
Running migrations...
== Applying 0001_basic-schema.up.sql ==
== Completed in 40 ms ==
Creating database projectname-test

Database projectname-test created successfully.
Running migration on postgres://didip@localhost:5432/projectname-test?sslmode=disable...
== Applying 0001_basic-schema.up.sql ==
== Completed in 14 ms ==
2016/07/17 17:36:49 Running go get ./...
2016/07/17 17:36:55 Running go test ./...
2016/07/17 17:36:56 ?   	github.com/tristor/projectname	[no test files]
?   	github.com/tristor/projectname/application	[no test files]
?   	github.com/tristor/projectname/handlers	[no test files]
ok  	github.com/tristor/projectname/libhttp	0.020s
ok  	github.com/tristor/projectname/libstring	0.011s
ok  	github.com/tristor/projectname/libunix	0.023s
?   	github.com/tristor/projectname/middlewares	[no test files]
ok  	github.com/tristor/projectname/models	0.224s
```

Does `createdb projectname-test` work?

**Comment by rnubel** [comment] 2016-07-18 03:03
@Tristor that's pretty crazy! Thanks @didip for verifying that the problem isn't global for El Capitan users. @Tristor, are you still replacing your actual project name with `projectname` manually for this output, or is it actually `projectname`? My best guess is that there's some character that's breaking the regex which we're not discerning (like a linebreak, or non-breaking space).

To try and prove that hypothesis, can you try replacing the URL-matching regexp with this regexp:

```go
r := regexp.MustCompile("^postgres://(.*)@(.*):([0-9]+)/([^?]+)")
```

That modified regexp makes the database name matcher less restrictive. If that still does not work, try this one, which explicitly tries to match until the end of the string.

```go
r := regexp.MustCompile("^postgres://(.*)@(.*):([0-9]+)/([^?]+)\\??.*$")
```

**Comment by Tristor** [comment] 2016-07-21 10:00
Sorry about the delay in my reply.  I'm traveling, so didn't have a moment to dedicate to this yet.  So just to clarify I was replacing the name of the actual project with `projectname` in my provided information above.  I retested this using a dummy project name that matches my actual name better and was able to reproduce the error directly.  It appears its an issue because the `.` character is in the name of the project, since it's the name of the domain it will be deployed to.

```
~GOPATH
❯ $GOPATH/bin/go-bootstrap -dir github.com/tristor/project.example.com -template postgresql
2016/07/21 11:58:32 Creating /Users/tristor/projects/go/src/github.com/tristor/project.example.com...
2016/07/21 11:58:32 Copying project template directory to /Users/tristor/projects/go/src/github.com/tristor/project.example.com...
2016/07/21 11:58:32 Replacing placeholder variables on tristor/project.example.com...
2016/07/21 11:58:32 Running go get -u github.com/rnubel/pgmgr...
2016/07/21 11:58:40 Creating database project.example.com...
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com?sslmode=disable
project
[postgres://tristor@localhost:5432/project tristor localhost 5432 project]
-- End Issue 47 Log --

Database project created successfully.
Running migrations...
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com?sslmode=disable
project
[postgres://tristor@localhost:5432/project tristor localhost 5432 project]
-- End Issue 47 Log --
== Applying 0001_basic-schema.up.sql ==
== Completed in 9 ms ==
Creating database project.example.com-test
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable
project
[postgres://tristor@localhost:5432/project tristor localhost 5432 project]
-- End Issue 47 Log --
createdb: database creation failed: ERROR:  database "project" already exists

Error:  exit status 1

Running migration on postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable...
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable
project
[postgres://tristor@localhost:5432/project tristor localhost 5432 project]
-- End Issue 47 Log --
Nothing to do; all migrations already applied.
2016/07/21 11:58:40 Running go get ./...
2016/07/21 11:58:43 Running go test ./...
2016/07/21 11:58:44 ?   	github.com/tristor/project.example.com	[no test files]
?   	github.com/tristor/project.example.com/application	[no test files]
?   	github.com/tristor/project.example.com/handlers	[no test files]
ok  	github.com/tristor/project.example.com/libhttp	0.008s
ok  	github.com/tristor/project.example.com/libstring	0.014s
ok  	github.com/tristor/project.example.com/libunix	0.009s
?   	github.com/tristor/project.example.com/middlewares	[no test files]
--- FAIL: TestNewTransactionIfNeeded (0.01s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
--- FAIL: TestCreateDeleteGeneric (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
--- FAIL: TestCreateDeleteById (0.01s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
--- FAIL: TestCreateUpdateGenericDelete (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
--- FAIL: TestCreateUpdateByIDDelete (0.01s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
--- FAIL: TestCreateUpdateByKeyValueStringDelete (0.00s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
--- FAIL: TestUserCRUD (0.01s)
	base_test.go:41: Connecting to local postgres should never fail. Error: pq: database "project.example.com-test" does not exist
FAIL
FAIL	github.com/tristor/project.example.com/models	0.046s
```

**Comment by Tristor** [comment] 2016-07-21 10:04
Using this for the regexp appears to resolve the issue @rnubel :
`r := regexp.MustCompile("^postgres://(.*)@(.*):([0-9]+)/([^?]+)")`

```
~GOPATH/src/github.com/tristor/project.example.com
❯ $GOPATH/bin/pgmgr -c .pgmgr.test.json config
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable
project.example.com-test
[postgres://tristor@localhost:5432/project.example.com-test tristor localhost 5432 project.example.com-test]
-- End Issue 47 Log --
&{Username:tristor Password: Database:project.example.com-test Host:localhost Port:5432 URL:postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable SslMode:disable DumpFile:migrations/dump.sql MigrationFolder:migrations MigrationTable:schema_migrations SeedTables:[] ColumnType:integer Format:unix}
```

**Comment by Tristor** [comment] 2016-07-21 10:05
Running through the full `go-bootstrap` process afterwards seems to succeed without issues.

```
~GOPATH/src/github.com/tristor
❯ $GOPATH/bin/go-bootstrap -dir github.com/tristor/project.example.com -template postgresql
2016/07/21 12:04:52 Creating /Users/tristor/projects/go/src/github.com/tristor/project.example.com...
2016/07/21 12:04:52 Copying project template directory to /Users/tristor/projects/go/src/github.com/tristor/project.example.com...
2016/07/21 12:04:52 Replacing placeholder variables on tristor/project.example.com...
2016/07/21 12:04:52 Running go get -u github.com/rnubel/pgmgr...
2016/07/21 12:04:56 Creating database project.example.com...
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com?sslmode=disable
project.example.com
[postgres://tristor@localhost:5432/project.example.com tristor localhost 5432 project.example.com]
-- End Issue 47 Log --

Database project.example.com created successfully.
Running migrations...
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com?sslmode=disable
project.example.com
[postgres://tristor@localhost:5432/project.example.com tristor localhost 5432 project.example.com]
-- End Issue 47 Log --
== Applying 0001_basic-schema.up.sql ==
== Completed in 7 ms ==
Creating database project.example.com-test
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable
project.example.com-test
[postgres://tristor@localhost:5432/project.example.com-test tristor localhost 5432 project.example.com-test]
-- End Issue 47 Log --

Database project.example.com-test created successfully.
Running migration on postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable...
-- Start Issue 47 Log --
postgres://tristor@localhost:5432/project.example.com-test?sslmode=disable
project.example.com-test
[postgres://tristor@localhost:5432/project.example.com-test tristor localhost 5432 project.example.com-test]
-- End Issue 47 Log --
== Applying 0001_basic-schema.up.sql ==
== Completed in 8 ms ==
2016/07/21 12:04:56 Running go get ./...
2016/07/21 12:04:58 Running go test ./...
2016/07/21 12:04:59 ?   	github.com/tristor/project.example.com	[no test files]
?   	github.com/tristor/project.example.com/application	[no test files]
?   	github.com/tristor/project.example.com/handlers	[no test files]
ok  	github.com/tristor/project.example.com/libhttp	0.008s
ok  	github.com/tristor/project.example.com/libstring	0.005s
ok  	github.com/tristor/project.example.com/libunix	0.010s
?   	github.com/tristor/project.example.com/middlewares	[no test files]
ok  	github.com/tristor/project.example.com/models	0.068s
```

**Comment by rnubel** [comment] 2016-07-21 15:30
Ah ha! So the issue is definitely the period character, which I didn't know is a valid character in database names. This is a bug in pgmgr -- it should support any database name that's valid in Postgres. I'll get a patch ready shortly. I'm glad we got to the bottom of this! Thanks for being so helpful in debugging.

**Comment by rnubel** [comment] 2016-07-21 16:59
The fix has been merged in (https://github.com/rnubel/pgmgr/issues/29), so this issue should be resolved.

**Comment by Tristor** [comment] 2016-07-27 11:31
I can confirm that the fix appears to work correctly for me.  We can close this issue.  Thanks @rnubel !

**Closed** 2016-07-27 11:32 UTC
